### ISSUE TITLE
Transposed GC Implementation

### ISSUE THREAD

**Issue by jridgewell** [erights/PLNSOWNSF#2]
> using the transposed representation (as Chakra does), so that the state is actually in a table hung off the key, indexed by the PrivateName identity.

Can you explain why this is necessary?

**Comment by erights** [comment]
When the instance is the key, the instance holds onto the class, the class holds only the PrivateName. Thus, the PrivateName's lifetime is at least as long as the lifetime of any of the instances that use it.

If you store the instance->value association in the PrivateName, then it will survive the first pass of gc, which is the normal non-ephemeron gc algorithm. These associations will only get collected by a later ephemeron collection algorithm which is *much* more expensive.

If you store the PrivateName->value association in the instance, then normal collection of the instance will collect the association as well without special work. If the value in question is referred to only by that association, then it gets collected as well, again without any special work. The reference topology is exactly what we currently have with internal slots and that you would anticipate from private symbols, and so it has the same gc perf as those.

Granted WeakMaps are meant to cover more cases than PrivateName. Which is the right choice depends on whether keys tend to outlive maps, or vice versa. When I tried to break this down by use case, @wycats pointed out that most of my keys-live-longer cases were ones where you'd probably use a Map rather than a WeakMap anyway.

Chakra does all WeakMaps with the transposed representation. @bterlson, did you ever encounter a case where you were unhappy with the GC performance profile that resulted from this decision?
